web_configuration:
  web_path: /var/www/path/to/website
  tarfile: WebArchive_
  web_ext: .tar.gz
  mode: w|gz

db_configuration:
  back_name: db_backup_
  db_name: database_name
  back_path: /path/to/your/backup/folder
  back_ext: .sql
  db_user: your_admin_user

transfert:
  backup_user: username_of_distant_server 
  server_ip: ip_adress_of_distant_server 
  port: 22
  directory: /path/to/your/distant/backup/folder
